version: '3'

services:
  dev:
    build:
      context: .
      args:
        UBUNTU_VERSION: 22.04
        APT_MIRROR: http://jp.archive.ubuntu.com/ubuntu/
        USERNAME: vscode
        GO_VERSION: 1.21.6
      dockerfile: Dockerfile
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - type: bind
        source: ..
        target: /workspace
        consistency: cached
      - type: volume
        source: extensions
        target: /home/vscode/.vscode-server/extensions
      - type: bind
        source: .bash
        target: /home/vscode/.cache/bash
        consistency: delegated
      - type: volume
        source: go
        target: /home/vscode/go
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      GOPRIVATE: github.com/kurusugawa-computer/*
    init: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

volumes:
  extensions:
  go:
